apiVersion: batch/v1
kind: Job
metadata:
  name: userservice-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: userservice-migration
          image: nikirenegade/ihb-userservice:1.0.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: userservice-secret